[package]
name = "neon-poc"
version = "0.1.0"
authors = ["yagoff <yferrofigueira@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_poc"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.18"

[dependencies]
neon = "0.1.18"
